/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class libbiseccion_JavaBiseccion */

#ifndef _Included_libbiseccion_JavaBiseccion
#define _Included_libbiseccion_JavaBiseccion
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     libbiseccion_JavaBiseccion
 * Method:    biseccion
 * Signature: (DDII)[[D
 */
JNIEXPORT jobjectArray JNICALL Java_libbiseccion_JavaBiseccion_biseccion
  (JNIEnv *, jobject, jdouble, jdouble, jint, jint);

/*
 * Class:     libbiseccion_JavaBiseccion
 * Method:    iteraciones
 * Signature: (DDID)I
 */
JNIEXPORT jint JNICALL Java_libbiseccion_JavaBiseccion_iteraciones
  (JNIEnv *, jobject, jdouble, jdouble, jint, jdouble);

#ifdef __cplusplus
}
#endif
#endif
